version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash start.sh
    env_file:
      - ./Docker/api.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A aitarget_books worker -l info
    env_file:
      - ./Docker/api.env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
